version: 1.0
workflows:
  - name: countNs_slow
    subclass: WDL
    primaryDescriptorPath: /unknown_nt_counter.wdl
  - name: countNs_fast
    subclass: WDL
    primaryDescriptorPath: /unknown_nt_counter.wdl